"""added likely errors column

Revision ID: 033ac67f7345
Revises: ba2579a4c5a5
Create Date: 2020-06-02 12:39:42.350449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033ac67f7345'
down_revision = 'ba2579a4c5a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('likely_errors', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'likely_errors')
    # ### end Alembic commands ###
