"""added page response table

Revision ID: eb43f807e48d
Revises: 033ac67f7345
Create Date: 2020-06-02 13:18:36.556778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb43f807e48d'
down_revision = '033ac67f7345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('page_response', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'page_response')
    # ### end Alembic commands ###
